# -*- coding: utf-8 -*-
"""JalaVerdiyeva_ctrishers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sYrGj2GO7s0l8NWl3K2I3g4wfia-rDt

Will this article go viral?


Every day, news sites publish hundreds of articles, but only some of them become popular.

Can you predict which ones, before they are published?


In this competition you'll use real data from about 40,000 articles published on Mashable.


For each article you get simple, understandable features: title and article length, number of images and videos, the news section, the day of the week it was published, how positive or negative the text sounds, and how popular its keywords were in the past.


Your task is to predict whether an article becomes popular, meaning it received 1,400 or more social media shares.



This competition rewards solid ML skills:

🫡 exploring the data,

🫡 transforming skewed features,

🫡 encoding categorical variables,

🫡 reducing correlated feature groups with techniques like PCA, and

🫡 building models that generalize to future articles.


The test set contains articles published later than those in the training set.

# **box 1: importlar və data yüklənməsi 📦**
"""

# gərəkli kitabxanaları yükləyirik 😊
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from lightgbm import LGBMClassifier

# datanı oxuyuruq 📑
train_df = pd.read_csv("train.csv")

# target və feature-ları ayırırıq ✨
X = train_df.drop(columns=["target", "id", "publish_date", "publish_dateTime"], errors="ignore") # "publish_date", "publish_dateTime" yerine biz weekday saxlayiriq
y = train_df["target"]

print("data ölçüsü:", X.shape)

"""box 1.5: train datanı anlamaq və eda 🔍"""

# datanın ilk 5 sətrinə baxırıq 👀
display(train_df.head())

# sütun tipləri, boş dəyərlər və ümumi məlumat 📋
print("--- data info ---")
train_df.info()

# sütunların tiplərinin sayına baxırıq 🔢
print("\n--- data types count ---")
print(train_df.dtypes.value_counts())

# ədədi sütunların statistik xülasəsi (mean, min, max və s.) 📊
display(train_df.describe().T.round(2))

# target (hədəf) dəyişəninin balansı 🎯
print("\n--- target balansı (viral vs viral deyil) ---")
print(train_df["target"].value_counts(normalize=True).round(3))

"""yeni burda 1 və 0 sayı demək olar ki bərabərdir

# **box 2: eda və skewed xüsusiyyətlərin düzəldilməsi 📊**
"""

# kateqoriya və ədədi sütunları seçirik 🔍
categorical_cols = ["weekday", "channel"] # categorik lan tek 2ki birinci sutunlar var
numeric_cols = [c for c in X.columns if c not in categorical_cols]

# eğri (skewed) göstəriciləri log1p ilə düzəldirik 🎯
for col in numeric_cols:
    if X[col].skew() > 1.5:
        X[col] = np.log1p(np.maximum(0, X[col]))

print("skewness düzəldildi 👍")

"""# **box 3: preprocessing, pca və train-test split ⚙️**"""

# reducing correlated features edirik

# numeric scaling və pca əlavə edirik 🧪
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=0.95, random_state=42))
])

# categorical variables üçün one hot 🔤
categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocess = ColumnTransformer([
    ("num", numeric_transformer, numeric_cols),
    ("cat", categorical_transformer, categorical_cols)
])

# train və test olaraq bölürük (80/20) ✂️
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

"""# **box 4: task 1 - logistic regression (class weight balanced) ⚖️**"""

# standart və balanced logistic regression qururuq 🤖
lr_std = Pipeline([("prep", preprocess), ("model", LogisticRegression(max_iter=1000, random_state=42))])
lr_bal = Pipeline([("prep", preprocess), ("model", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42))])

lr_std.fit(X_train, y_train)
lr_bal.fit(X_train, y_train)

y_pred_std = lr_std.predict(X_test)
y_pred_bal = lr_bal.predict(X_test)

# nəticələri müqayisə edirik 📈
comp_df = pd.DataFrame({
    "standart lr": [
        precision_score(y_test, y_pred_std),
        recall_score(y_test, y_pred_std),
        f1_score(y_test, y_pred_std),
        roc_auc_score(y_test, lr_std.predict_proba(X_test)[:, 1])
    ],
    "balanced lr": [
        precision_score(y_test, y_pred_bal),
        recall_score(y_test, y_pred_bal),
        f1_score(y_test, y_pred_bal),
        roc_auc_score(y_test, lr_bal.predict_proba(X_test)[:, 1])
    ]
}, index=["precision", "recall", "f1", "roc-auc"])

display(comp_df.round(3))

"""mence burda yeni 1-lər azca çoxluq təşkil edirdi ona gore biraz bele fergli neticeler verdi

# **box 5: task 2 - lightgbm auc tuning 🚀**
"""

# lightgbm modelini optmallaşdırırıq 🔥
lgbm_tuned = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.02,
    num_leaves=31,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.7,
    random_state=42,
    verbose=-1
)

pipe_lgbm = Pipeline([("prep", preprocess), ("model", lgbm_tuned)])
pipe_lgbm.fit(X_train, y_train)

lgbm_proba = pipe_lgbm.predict_proba(X_test)[:, 1]
lgbm_auc = roc_auc_score(y_test, lgbm_proba)

print(f"yeni lightgbm roc-auc skoru: {lgbm_auc:.4f} 🎉")

"""# **box 6: task 3 - shap waterfall izahı (10-cu məqalə) 🌊**"""

# test datasından 10-cu məqaləni götürürük 📌
sample_idx = 10
sample_article = X_test.iloc[[sample_idx]]

model_obj = pipe_lgbm.named_steps["model"]
prep_obj = pipe_lgbm.named_steps["prep"]

sample_transformed = prep_obj.transform(sample_article)

# shap ilə izah edirik 🕵️‍♂️
explainer = shap.TreeExplainer(model_obj)
shap_values = explainer(sample_transformed)

print(f"həqiqi status: {y_test.iloc[sample_idx]}")
print(f"modelin verdiyi viral ehtimalı: {pipe_lgbm.predict_proba(sample_article)[0, 1]:.3f}")

plt.figure(figsize=(9, 6))
shap.plots.waterfall(shap_values[0], max_display=10)

import pandas as pd

# 1. Тесттік деректерді және үлгі ретінде берілген submission файлын жүктеңіз
test_df = pd.read_csv("test.csv")  # немесе сіздегі test файлының аты
sample_sub = pd.read_csv("sample_submission.csv")

# 2. Моделіңізбен test_df үшін болжам жасаңыз
# (Мысалы, pipe_lgbm моделі қолданылса)
predictions = pipe_lgbm.predict(test_df)  # немесе predict_proba(test_df)[:, 1]

# 3. Үлгідегі бағандарға сәйкес мандерді жазыңыз
sample_sub["target"] = predictions  # баған атын sample_submission.csv форматына сай қойыңыз

# 4. Дұрыс CSV файлын сақтаңыз
sample_sub.to_csv("submission.csv", index=False)

# 5. Файлды жүктеп алу (Colab қолдансаңыз)
from google.colab import files

files.download("submission.csv")

"""--------------------------------------------------------------------------------------


## here are several attempts with AI after here below


"""

# ==============================================================================
# BOX 1: Imports and Data Loading 📦                                            |
# ==============================================================================
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import shap
from lightgbm import LGBMClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Read training data
train_df = pd.read_csv("train.csv")

# Separate target and features
X = train_df.drop(
    columns=["target", "id", "publish_date", "publish_dateTime"], errors="ignore"
)
y = train_df["target"]

print("Training Data Shape:", X.shape)


# ==============================================================================
# BOX 2: Skewness Correction 📊                                                 |
# ==============================================================================
categorical_cols = ["weekday", "channel"]
numeric_cols = [c for c in X.columns if c not in categorical_cols]

# Apply log1p transformation to heavily skewed numerical features
for col in numeric_cols:
  if X[col].skew() > 1.5:
    X[col] = np.log1p(np.maximum(0, X[col]))

print("Skewness transformation applied successfully 👍")

# ==============================================================================
# BOX 3: Preprocessing Pipelines ⚙️                                             |
# ==============================================================================
numeric_transformer_tree = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])

preprocess_tree = ColumnTransformer(
    [
        ("num", numeric_transformer_tree, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    verbose_feature_names_out=False,
)

# Sütun isimlerini korumak için Pandas çıktısını aktif ediyoruz:
preprocess_tree.set_output(transform="pandas")

# Train / Validation split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


# ==============================================================================
# BOX 4: Model Training (LightGBM) 🚀                                           |
# ==============================================================================
lgbm_tuned = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.02,
    num_leaves=31,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.7,
    random_state=42,
    verbose=-1,
)

pipe_lgbm = Pipeline([("prep", preprocess_tree), ("model", lgbm_tuned)])

# Fit on validation split
pipe_lgbm.fit(X_train, y_train)

lgbm_proba_val = pipe_lgbm.predict_proba(X_val)[:, 1]
lgbm_auc_val = roc_auc_score(y_val, lgbm_proba_val)

print(f"Validation ROC-AUC Score: {lgbm_auc_val:.4f} 🎉")


# ==============================================================================
# BOX 5: SHAP Explanation for 10th Article 🌊                                   |
# ==============================================================================
sample_idx = 10
sample_article = X_val.iloc[[sample_idx]]

model_obj = pipe_lgbm.named_steps["model"]
prep_obj = pipe_lgbm.named_steps["prep"]

# Sütun isimli DataFrame elde ediyoruz
sample_transformed = prep_obj.transform(sample_article)

# TreeExplainer ile SHAP hesaplama
explainer = shap.TreeExplainer(model_obj)
shap_values = explainer(sample_transformed)

print(f"True status: {y_val.iloc[sample_idx]}")
print(
    "Predicted probability:"
    f" {pipe_lgbm.predict_proba(sample_article)[0, 1]:.3f}"
)

# Waterfall grafiği (artık Feature 55 yerine gerçek adlar görünecek)
plt.figure(figsize=(9, 6))
shap.plots.waterfall(shap_values[0], max_display=10)

# ==============================================================================
# BOX 6: Final Inference & Correct Submission File Generation 📥                |
# ==============================================================================
# 1. Fit the pipeline on the FULL training dataset for maximum accuracy
pipe_lgbm.fit(X, y)

# 2. Load test data and submission template
test_df = pd.read_csv("test.csv")
sample_sub = pd.read_csv("sample_submission.csv")

# 3. Prepare test features (matching training columns)
X_test = test_df.drop(
    columns=["id", "target", "publish_date", "publish_dateTime"], errors="ignore"
).copy()

# 4. Apply skewness transformation to test features
for col in numeric_cols:
  if col in X_test.columns:
    if X_test[col].skew() > 1.5:
      X_test[col] = np.log1p(np.maximum(0, X_test[col]))

# 5. Predict PROBABILITIES (crucial for ROC-AUC score)
test_predictions_proba = pipe_lgbm.predict_proba(X_test)[:, 1]

# 6. Assign probabilities to submission dataframe
target_col = [c for c in sample_sub.columns if c != "id"][0]
sample_sub[target_col] = test_predictions_proba

# 7. Save and download submission file
sample_sub.to_csv("submission.csv", index=False)

try:
  from google.colab import files

  files.download("submission.csv")
except ImportError:
  print("Submission saved locally as submission.csv")

her# ==============================================================================
# BOX 1: İdxallar və Datanın Yüklənməsi 📦
# ==============================================================================
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
from lightgbm import LGBMClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Datanı oxuyuruq
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
sample_sub = pd.read_csv("sample_submission.csv")


# ==============================================================================
# BOX 2: Feature Engineering (Yeni Xüsusiyyətlərin Yaradılması) 🛠️
# ==============================================================================
def create_features(df):
  df_feat = df.copy()

  # Görsel və linklərin mətn sıxlığına nisbəti
  df_feat["words_per_img"] = df_feat["n_tokens_content"] / (
      df_feat["num_imgs"] + 1
  )
  df_feat["words_per_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_hrefs"] + 1
  )
  df_feat["words_per_self_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_self_hrefs"] + 1
  )

  # Anahtar söz və başlıq nisbətləri
  df_feat["kw_avg_ratio"] = df_feat["kw_max_avg"] / (
      df_feat["kw_avg_avg"] + 1e-5
  )
  df_feat["title_content_ratio"] = df_feat["n_tokens_title"] / (
      df_feat["n_tokens_content"] + 1
  )

  # Həftəsonu indikatoru
  if "weekday" in df_feat.columns:
    df_feat["is_weekend"] = (
        df_feat["weekday"].isin(["Saturday", "Sunday"]).astype(int)
    )

  return df_feat


# Target və Feature-ları ayırırıq
X = train_df.drop(
    columns=["target", "id", "publish_date", "publish_dateTime"], errors="ignore"
)
y = train_df["target"]

X_test = test_df.drop(
    columns=["id", "target", "publish_date", "publish_dateTime"], errors="ignore"
)

# Feature engineering tətbiqi
X = create_features(X)
X_test = create_features(X_test)

# Skewness (Əğrilik) düzəldilməsi
categorical_cols = ["weekday", "channel"]
numeric_cols = [c for c in X.columns if c not in categorical_cols]

for col in numeric_cols:
  if X[col].skew() > 1.5:
    X[col] = np.log1p(np.maximum(0, X[col]))
    if col in X_test.columns:
      X_test[col] = np.log1p(np.maximum(0, X_test[col]))

print("Feature Engineering və Skewness tamamlandı 👍")


# ==============================================================================
# BOX 3: Preprocessing Pipeline (Pandas Çıxışı İlə) ⚙️
# ==============================================================================
numeric_transformer_tree = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])

preprocess_tree = ColumnTransformer(
    [
        ("num", numeric_transformer_tree, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    verbose_feature_names_out=False,
)

# Sütun adlarını qorumaq üçün Pandas DataFrame çıxışı
preprocess_tree.set_output(transform="pandas")


# ==============================================================================
# BOX 4: SHAP Analizi (Lokal Nümunə İzahı) 🌊
# ==============================================================================
X_train_sub, X_val_sub, y_train_sub, y_val_sub = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

lgbm_single = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.02,
    num_leaves=31,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.7,
    random_state=42,
    verbose=-1,
)

pipe_single = Pipeline([("prep", preprocess_tree), ("model", lgbm_single)])
pipe_single.fit(X_train_sub, y_train_sub)

sample_idx = 10
sample_article = X_val_sub.iloc[[sample_idx]]
sample_transformed = pipe_single.named_steps["prep"].transform(sample_article)

explainer = shap.TreeExplainer(pipe_single.named_steps["model"])
shap_values = explainer(sample_transformed)

plt.figure(figsize=(9, 6))
shap.plots.waterfall(shap_values[0], max_display=10)


# ==============================================================================
# BOX 5: 5-Fold Stratified CV Modelləməsi & Ansambl Tahminlər 🚀
# ==============================================================================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

test_predictions = np.zeros(len(X_test))
oof_predictions = np.zeros(len(X))

lgbm_model = LGBMClassifier(
    n_estimators=800,
    learning_rate=0.015,
    num_leaves=28,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.7,
    random_state=42,
    verbose=-1,
)

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
  X_tr, y_tr = X.iloc[train_idx], y.iloc[train_idx]
  X_va, y_va = X.iloc[val_idx], y.iloc[val_idx]

  pipeline = Pipeline([("prep", preprocess_tree), ("model", lgbm_model)])
  pipeline.fit(X_tr, y_tr)

  # Out-of-fold validation ehtimalları
  val_preds = pipeline.predict_proba(X_va)[:, 1]
  oof_predictions[val_idx] = val_preds

  # Test set təxminlərinin toplanması
  test_predictions += pipeline.predict_proba(X_test)[:, 1] / skf.n_splits

  fold_auc = roc_auc_score(y_va, val_preds)
  print(f"Fold {fold+1} ROC-AUC Score: {fold_auc:.4f}")

overall_cv_auc = roc_auc_score(y, oof_predictions)
print(f"\nOverall 5-Fold OOF ROC-AUC Score: {overall_cv_auc:.4f} 🎉")


# ==============================================================================
# BOX 6: Yekun Submission Faylının Hazırlanması 📥
# ==============================================================================
target_col = [c for c in sample_sub.columns if c != "id"][0]
sample_sub[target_col] = test_predictions

sample_sub.to_csv("submission_kfold.csv", index=False)

try:
  from google.colab import files

  files.download("submission_kfold.csv")
except ImportError:
  print("Fayl lokal olaraq 'submission_kfold.csv' adı ilə saxlanıldı.")

# ==============================================================================
# BOX 1: Kütüphaneler ve Veri Yükleme 📦
# ==============================================================================
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBClassifier

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
sample_sub = pd.read_csv("sample_submission.csv")


# ==============================================================================
# BOX 2: Feature Engineering (Gelişmiş Özellik Türetme) 🛠️
# ==============================================================================
def create_features(df):
  df_feat = df.copy()

  # İçerik ve Medya Yoğunlukları
  df_feat["words_per_img"] = df_feat["n_tokens_content"] / (
      df_feat["num_imgs"] + 1
  )
  df_feat["words_per_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_hrefs"] + 1
  )
  df_feat["words_per_self_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_self_hrefs"] + 1
  )

  # Anahtar Kelime & Başlık Oranları
  df_feat["kw_avg_ratio"] = df_feat["kw_max_avg"] / (
      df_feat["kw_avg_avg"] + 1e-5
  )
  df_feat["kw_min_ratio"] = df_feat["kw_max_min"] / (
      df_feat["kw_avg_min"] + 1e-5
  )
  df_feat["title_content_ratio"] = df_feat["n_tokens_title"] / (
      df_feat["n_tokens_content"] + 1
  )

  # Duygu Sezgiselliği Etkileşimi
  df_feat["polarity_interaction"] = (
      df_feat["global_sentiment_polarity"]
      * df_feat["global_subjectivity"]
  )

  # Hafta Sonu Etkisi
  if "weekday" in df_feat.columns:
    df_feat["is_weekend"] = (
        df_feat["weekday"].isin(["Saturday", "Sunday"]).astype(int)
    )

  return df_feat


X = train_df.drop(
    columns=["target", "id", "publish_date", "publish_dateTime"], errors="ignore"
)
y = train_df["target"]
X_test = test_df.drop(
    columns=["id", "target", "publish_date", "publish_dateTime"], errors="ignore"
)

X = create_features(X)
X_test = create_features(X_test)

categorical_cols = ["weekday", "channel"]
numeric_cols = [c for c in X.columns if c not in categorical_cols]

# Skewness Düzeltmesi
for col in numeric_cols:
  if X[col].skew() > 1.5:
    X[col] = np.log1p(np.maximum(0, X[col]))
    if col in X_test.columns:
      X_test[col] = np.log1p(np.maximum(0, X_test[col]))


# ==============================================================================
# BOX 3: Preprocessing Pipeline ⚙️
# ==============================================================================
numeric_transformer_tree = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])

preprocess_tree = ColumnTransformer(
    [
        ("num", numeric_transformer_tree, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    verbose_feature_names_out=False,
)
preprocess_tree.set_output(transform="pandas")


# ==============================================================================
# BOX 4: 5-Fold Cross Validation ile Multi-Model Ensemble 🚀
# ==============================================================================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

preds_lgb = np.zeros(len(X_test))
preds_cat = np.zeros(len(X_test))
preds_xgb = np.zeros(len(X_test))

# Pipeline ile veriyi dönüştürelim
X_trans = preprocess_tree.fit_transform(X)
X_test_trans = preprocess_tree.transform(X_test)

print("Eğitim Başlıyor...\n")

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trans, y)):
  X_tr, y_tr = X_trans.iloc[train_idx], y.iloc[train_idx]
  X_va, y_va = X_trans.iloc[val_idx], y.iloc[val_idx]

  # 1. LightGBM
  model_lgb = LGBMClassifier(
      n_estimators=800,
      learning_rate=0.015,
      num_leaves=28,
      max_depth=6,
      subsample=0.8,
      colsample_bytree=0.7,
      random_state=42,
      verbose=-1,
  )
  model_lgb.fit(X_tr, y_tr)
  preds_lgb += model_lgb.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  # 2. CatBoost
  model_cat = CatBoostClassifier(
      iterations=800,
      learning_rate=0.02,
      depth=6,
      random_seed=42,
      verbose=0,
  )
  model_cat.fit(X_tr, y_tr)
  preds_cat += model_cat.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  # 3. XGBoost
  model_xgb = XGBClassifier(
      n_estimators=700,
      learning_rate=0.015,
      max_depth=5,
      subsample=0.8,
      colsample_bytree=0.7,
      random_state=42,
      eval_metric="auc",
  )
  model_xgb.fit(X_tr, y_tr)
  preds_xgb += model_xgb.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  print(f"Fold {fold+1} modelleri eğitildi.")

# Modellerin Ağırlıklı Ortalaması (Ensemble)
final_ensemble_preds = (
    (0.50 * preds_lgb) + (0.30 * preds_cat) + (0.20 * preds_xgb)
)


# ==============================================================================
# BOX 5: Submission Dosyasını Oluşturma 📥
# ==============================================================================
target_col = [c for c in sample_sub.columns if c != "id"][0]
sample_sub[target_col] = final_ensemble_preds

sample_sub.to_csv("submission_ensemble.csv", index=False)

try:
  from google.colab import files

  files.download("submission_ensemble.csv")
except ImportError:
  print("Dosya 'submission_ensemble.csv' adıyla kaydedildi.")

# ==============================================================================
# BOX 1: Kütüphaneler ve Datanın Hazırlanması 📦
# ==============================================================================
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from scipy.stats import rankdata
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBClassifier

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
sample_sub = pd.read_csv("sample_submission.csv")


# ==============================================================================
# BOX 2: Gelişmiş Özellik Mühendisliği (Advanced Feature Engineering) 🛠️️
# ==============================================================================
def create_advanced_features(df):
  df_feat = df.copy()

  # 1. Medya ve Kelime Oranları
  df_feat["words_per_img"] = df_feat["n_tokens_content"] / (
      df_feat["num_imgs"] + 1
  )
  df_feat["words_per_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_hrefs"] + 1
  )
  df_feat["words_per_self_href"] = df_feat["n_tokens_content"] / (
      df_feat["num_self_hrefs"] + 1
  )

  # 2. Anahtar Kelime & Başlık Etkileşimleri
  df_feat["kw_avg_ratio"] = df_feat["kw_max_avg"] / (
      df_feat["kw_avg_avg"] + 1e-5
  )
  df_feat["kw_min_ratio"] = df_feat["kw_max_min"] / (
      df_feat["kw_avg_min"] + 1e-5
  )
  df_feat["title_content_ratio"] = df_feat["n_tokens_title"] / (
      df_feat["n_tokens_content"] + 1
  )

  # 3. Duygu Sezgiselliği Etkileşimi
  df_feat["polarity_interaction"] = (
      df_feat["global_sentiment_polarity"]
      * df_feat["global_subjectivity"]
  )
  df_feat["pos_neg_ratio"] = (df_feat["global_rate_positive_words"] + 1e-5) / (
      df_feat["global_rate_negative_words"] + 1e-5
  )

  # 4. Zaman ve Hafta Sonu Etkisi
  if "weekday" in df_feat.columns:
    df_feat["is_weekend"] = (
        df_feat["weekday"].isin(["Saturday", "Sunday"]).astype(int)
    )

  return df_feat


X = train_df.drop(
    columns=["target", "id", "publish_date", "publish_dateTime"], errors="ignore"
)
y = train_df["target"]
X_test = test_df.drop(
    columns=["id", "target", "publish_date", "publish_dateTime"], errors="ignore"
)

X = create_advanced_features(X)
X_test = create_advanced_features(X_test)

categorical_cols = ["weekday", "channel"]
numeric_cols = [c for c in X.columns if c not in categorical_cols]

# Skewness Düzeltmesi
for col in numeric_cols:
  if X[col].skew() > 1.5:
    X[col] = np.log1p(np.maximum(0, X[col]))
    if col in X_test.columns:
      X_test[col] = np.log1p(np.maximum(0, X_test[col]))


# ==============================================================================
# BOX 3: Preprocessing Pipeline ⚙️
# ==============================================================================
numeric_transformer_tree = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])

preprocess_tree = ColumnTransformer(
    [
        ("num", numeric_transformer_tree, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    verbose_feature_names_out=False,
)
preprocess_tree.set_output(transform="pandas")

X_trans = preprocess_tree.fit_transform(X)
X_test_trans = preprocess_tree.transform(X_test)


# ==============================================================================
# BOX 4: 5-Fold Stratified K-Fold CV ile Eğitme 🚀
# ==============================================================================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

preds_lgb = np.zeros(len(X_test))
preds_cat = np.zeros(len(X_test))
preds_xgb = np.zeros(len(X_test))

print("Modeller 5-Fold Cross Validation ile eğitiliyor...\n")

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trans, y)):
  X_tr, y_tr = X_trans.iloc[train_idx], y.iloc[train_idx]
  X_va, y_va = X_trans.iloc[val_idx], y.iloc[val_idx]

  # 1. LightGBM (Optimizasyonlu)
  model_lgb = LGBMClassifier(
      n_estimators=1000,
      learning_rate=0.012,
      num_leaves=31,
      max_depth=6,
      subsample=0.75,
      colsample_bytree=0.65,
      random_state=42 + fold,
      verbose=-1,
  )
  model_lgb.fit(X_tr, y_tr)
  preds_lgb += model_lgb.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  # 2. CatBoost (Optimizasyonlu)
  model_cat = CatBoostClassifier(
      iterations=1000,
      learning_rate=0.015,
      depth=6,
      l2_leaf_reg=3,
      random_seed=42 + fold,
      verbose=0,
  )
  model_cat.fit(X_tr, y_tr)
  preds_cat += model_cat.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  # 3. XGBoost (Optimizasyonlu)
  model_xgb = XGBClassifier(
      n_estimators=900,
      learning_rate=0.012,
      max_depth=5,
      subsample=0.75,
      colsample_bytree=0.65,
      random_state=42 + fold,
      eval_metric="auc",
  )
  model_xgb.fit(X_tr, y_tr)
  preds_xgb += model_xgb.predict_proba(X_test_trans)[:, 1] / skf.n_splits

  print(f"Fold {fold+1} tamamlandı.")


# ==============================================================================
# BOX 5: Rank Averaging (Sıralama Tabanlı Harmanlama) 🏆
# ==============================================================================
# Tahmin ehtimallarını sıralamaya dönüştürerek kalibre ediyoruz
rank_lgb = rankdata(preds_lgb) / len(preds_lgb)
rank_cat = rankdata(preds_cat) / len(preds_cat)
rank_xgb = rankdata(preds_xgb) / len(preds_xgb)

# Optimize edilmiş ağırlıklarla birleştirme
final_rank_ensemble = (
    (0.45 * rank_lgb) + (0.35 * rank_cat) + (0.20 * rank_xgb)
)


# ==============================================================================
# BOX 6: Yekun Submission Dosyasının Kaydedilmesi 📥
# ==============================================================================
target_col = [c for c in sample_sub.columns if c != "id"][0]
sample_sub[target_col] = final_rank_ensemble

sample_sub.to_csv("submission_advanced_ensemble.csv", index=False)

try:
  from google.colab import files

  files.download("submission_advanced_ensemble.csv")
except ImportError:
  print("Dosya 'submission_advanced_ensemble.csv' adı ile kaydedildi.")

